### PR TITLE
fix: add validation to avoid api tokens/databases creation with invalid name

### LINKED ISSUE #403: Place limits on valid characters for platform API tokens
I can create a token with nothing but invisible characters:

```
$ go run cmd/turso/main.go auth api-tokens create "   "

$ go run cmd/turso/main.go auth api-tokens list
NAME

```

I now have no easy way of identifying it in the list.

I can also attempt to embed other whitespace characters into the name.  Here are two tabs:

```
$ go run cmd/turso/main.go auth api-tokens create "               "
Error: failed to create token: parse "/v1/auth/api-tokens/\t\t": net/url: invalid control character in URL
exit status 1
```

It would be reasonable to place the same restrictions on token names as the names of databases.

### PR DESCRIPTION
**Pull request by StefanoSaffran**
This PR aims to add a validation to avoid API tokens creation with an invalid name.

closes #403

### CODE REVIEW

File: internal/cmd/auth_createapitokens.go [hunk 1]
```diff
@@ -27,7 +29,14 @@ var createApiTokensCmd = &cobra.Command{
 			return err
 		}
 
-		tokenName := args[0]
+		tokenName := strings.TrimSpace(args[0])
+
+		validNameRegex := regexp.MustCompile("^[a-zA-Z0-9_-]+$")
```
Comment (athoscouto) [inline internal/cmd/auth_createapitokens.go:34]: I think we should enforce the same rules for all entities' names.
The ones that we use for databases (on the server) seem good enough:

```go
func IsValidName(name string) bool {
	for _, r := range name {
		if !(unicode.IsDigit(r) || (unicode.IsLetter(r) && unicode.IsLower(r)) || r == '-') {
			return false
		}
	}
	return true
}
```

Let's use the same function here instead of regexes.
And since you're at it, please also validate database names before we send the request to the API.

Comment (athoscouto) [inline internal/cmd/auth_createapitokens.go:34]: It doesn't quite apply here, but in future uses of the `regexp` package please:
- Use `regexp.MustCompile` in a place that is clearly called once at the beginning of the program life (e.g. at the package level) and reused.
- Otherwise use `regexp.Compile`.

File: internal/cmd/auth_createapitokens.go [hunk 2]
```diff
@@ -27,7 +29,14 @@ var createApiTokensCmd = &cobra.Command{
...
+
+		if !validNameRegex.MatchString(tokenName) {
+			fmt.Println("Invalid token name, creation aborted.")
```
Comment (athoscouto) [inline internal/cmd/auth_createapitokens.go:37]: Please return an error to interrupt the program execution here.

**Comment by haaawk** [comment]
This is still a draft @athoscouto ;)

File: internal/cmd/auth_createapitokens.go (hunk 1 above)
Comment (StefanoSaffran) [reply internal/cmd/auth_createapitokens.go]: Thanks, I added the function and used it instead of regex.

File: internal/cmd/auth_createapitokens.go [hunk 3]
```diff
@@ -27,7 +29,15 @@ var createApiTokensCmd = &cobra.Command{
 			return err
 		}
 
-		tokenName := args[0]
+		tokenName := strings.TrimSpace(args[0])
+
+		isValid := turso.IsValidName(tokenName)
+
+		if !isValid {
```
Comment (athoscouto) [inline internal/cmd/auth_createapitokens.go:36]: ⛏️
```suggestion
		if !turso.IsValidName(tokenName) {
```

File: internal/cmd/db_create.go [hunk 4]
```diff
@@ -32,6 +33,13 @@ var createCmd = &cobra.Command{
 			return err
 		}
 
+		isValid := turso.IsValidName(name)
+
+		if !isValid {
```
Comment (athoscouto) [inline internal/cmd/db_create.go:38]: :pick: 
```suggestion
		if !turso.IsValidName(tokenName) {
```

File: internal/cmd/db_create.go [hunk 5]
```diff
@@ -32,6 +33,13 @@ var createCmd = &cobra.Command{
...
+			fmt.Println("Invalid name format. Please use only lowercase letters, numbers, and hyphens (-).")
+			return nil
```
Comment (athoscouto) [inline internal/cmd/db_create.go:40]:
```suggestion
			return errors.New("invalid name: names only support lowercase letters, numbers, and hyphens")
```

File: internal/cmd/auth_createapitokens.go [hunk 6]
```diff
@@ -27,7 +29,15 @@ var createApiTokensCmd = &cobra.Command{
...
+			fmt.Println("Invalid name format. Please use only lowercase letters, numbers, and hyphens (-).")
+			return nil
```
Comment (athoscouto) [inline internal/cmd/auth_createapitokens.go:38]:
```suggestion
			return errors.New("invalid name: names only support lowercase letters, numbers, and hyphens")
```

**Review by athoscouto — APPROVED** [review]
LGTM

A couple of nits regarding the `isValid` variable.

Also, we should try to act uniformly during error handling.
In general, we return an `error` instead of printing a message and returning `nil`.
Because [error strings should not be capitalized](https://github.com/golang/go/wiki/CodeReviewComments#error-strings), I've suggested a change in the error message.

**Review by haaawk — APPROVED** [review]
